---
- name: AWS Tag Management
  hosts: dev-rh
  tasks:
     - file:
        path: /tmp/notify
        state: directory
     - lineinfile:
         create: true
         line: "Non Compliant Instances in NONPROD"
         path: /tmp/noncompliantmachines.txt
         state: present
       name: "Create the noncompliant machines txt file for improperly tagged boxes"
